-- SCRIPTS TO TRANSFER SCHEMA FROM DBO TO STG
-- CREATE NEW SCHEMA
CREATE SCHEMA STG
GO

--  SYNTAX TO TRANSFER SCHEMA
ALTER SCHEMA STG
TRANSFER [dbo].[details]

-- TO TRANSFER MULTIPLE TABLES AT ONCE
SELECT 'ALTER SCHEMA STG TRANSFER ['+SCHEMA_NAME(SCHEMA_ID)+'].['+NAME+']' from sys.objects 
where SCHEMA_NAME(SCHEMA_ID) = 'dbo'

GO
SELECT * FROM SYS.objects
WHERE SCHEMA_NAME(SCHEMA_ID) = 'DBO'